/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 清翔越访客系统接口文档 - version 1.0
 *
 * 清翔越访客系统接口文档
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.detailUsingGET': ['GET', '/visitor/detail'],
  'general.exportAllVisitorDataUsingGET': ['GET', '/visitor/export/all'],
  'general.exportVisitorPageDataUsingGET': ['GET', '/visitor/export/page'],
  'general.getMobileByCodeUsingGET': ['GET', '/visitor/getUserIdByCode'],
  'general.cancelUsingGET': ['GET', '/visitor/mobile/cancel'],
  'general.examineUsingPOST': ['POST', '/visitor/mobile/examine'],
  'general.getUserByPhoneUsingGET': ['GET', '/visitor/mobile/getUserByPhone'],
  'general.mobileLoginUsingPOST': ['POST', '/visitor/mobile/login'],
  'general.mobileQueryPageUsingGET': ['GET', '/visitor/mobile/queryPage'],
  'general.visitRequestUsingPOST': ['POST', '/visitor/mobile/visitRequest'],
  'general.pcLoginUsingPOST': ['POST', '/visitor/pc/login'],
  'general.pcLogoutUsingPOST': ['POST', '/visitor/pc/logout'],
  'general.queryPageUsingGET': ['GET', '/visitor/queryPage'],
  'general.releaseVisitorUsingPost': ['POST', '/visitor/releaseVisitor']
};
