/* tslint:disable */
/* eslint-disable */
/**
 * 清翔越访客系统接口文档 - version 1.0
 *
 * 清翔越访客系统接口文档
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type Visitor = {
  /**
   * 审批意见
   */
  approvalOpinions?: string;
  /**
   * 审批时间
   * [required]
   */
  approvalTime: string;
  /**
   * 创建时间
   * [required]
   */
  createTime: string;
  /**
   * 删除标识
   */
  deleted?: number;
  /**
   * 邮箱
   */
  email?: string;
  /**
   * 性别 unknown-未知,male-男性,female-女性）
   */
  gender?: string;
  /**
   * 主键
   */
  id?: number;
  /**
   * 证件号码
   */
  identityNo?: string;
  /**
   * 证件类型（1-身份证,99-其他）
   */
  identityType?: string;
  /**
   * 是否同意
   */
  isAgree?: string;
  /**
   * 是否审批
   */
  isApproval?: string;
  /**
   * 是否取消
   */
  isCancel?: string;
  /**
   * 手机号
   * [required]
   */
  phone: string;
  /**
   * 车牌号码
   * [required]
   */
  plateNo: string;
  /**
   * 原因
   */
  reason?: string;
  /**
   * 受访者姓名
   * [required]
   */
  receptionistName: string;
  /**
   * 受访者手机号
   * [required]
   */
  receptionistPhone: string;
  /**
   * 受访者企业微信userId
   * [required]
   */
  receptionistUserId: string;
  /**
   * 访问开始时间
   * [required]
   */
  validBeginTime: string;
  /**
   * 访问结束时间
   * [required]
   */
  validEndTime: string;
  /**
   * 访客人数
   * [required]
   */
  visitorCount: number;
  /**
   * 访客单位
   * [required]
   */
  visitorDepartment: string;
  /**
   * 访客姓名
   * [required]
   */
  visitorName: string;
  /**
   * 访客类型（1 Contractor 2 Visitor）
   * [required]
   */
  visitorType: string;
};
export type R_Visitor_ = {
  code?: number;
  /**
   * Visitor
   * ---
   * 访客信息实体类
   */
  data?: Visitor;
  msg?: string;
  status?: string;
};
export type R = {
  code?: number;
  data?: object;
  msg?: string;
  status?: string;
};
export type Phone = {
  code?: string;
};
export type OrderItem = {
  asc?: boolean;
  column?: string;
};
export type Page_Visitor_ = {
  countId?: string;
  current?: number;
  maxLimit?: number;
  optimizeCountSql?: boolean;
  orders?: OrderItem[];
  pages?: number;
  records?: Visitor[];
  searchCount?: boolean;
  size?: number;
  total?: number;
};
export type R_Page_Visitor_ = {
  code?: number;
  /**
   * Page«Visitor»
   * ---
   */
  data?: Page_Visitor_;
  msg?: string;
  status?: string;
};
export type User = {
  password?: string;
  username?: string;
};
declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [GET] 查询详情
       *
       * **path:** /visitor/detail
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // id
       *   id?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   // [title] Visitor
       *   // 访客信息实体类
       *   data?: {
       *     // 审批意见
       *     approvalOpinions?: string
       *     // 审批时间
       *     // [required]
       *     approvalTime: string
       *     // 创建时间
       *     // [required]
       *     createTime: string
       *     // 删除标识
       *     deleted?: number
       *     // 邮箱
       *     email?: string
       *     // 性别 unknown-未知,male-男性,female-女性）
       *     gender?: string
       *     // 主键
       *     id?: number
       *     // 证件号码
       *     identityNo?: string
       *     // 证件类型（1-身份证,99-其他）
       *     identityType?: string
       *     // 是否同意
       *     isAgree?: string
       *     // 是否审批
       *     isApproval?: string
       *     // 是否取消
       *     isCancel?: string
       *     // 手机号
       *     // [required]
       *     phone: string
       *     // 车牌号码
       *     // [required]
       *     plateNo: string
       *     // 原因
       *     reason?: string
       *     // 受访者姓名
       *     // [required]
       *     receptionistName: string
       *     // 受访者手机号
       *     // [required]
       *     receptionistPhone: string
       *     // 受访者企业微信userId
       *     // [required]
       *     receptionistUserId: string
       *     // 访问开始时间
       *     // [required]
       *     validBeginTime: string
       *     // 访问结束时间
       *     // [required]
       *     validEndTime: string
       *     // 访客人数
       *     // [required]
       *     visitorCount: number
       *     // 访客单位
       *     // [required]
       *     visitorDepartment: string
       *     // 访客姓名
       *     // [required]
       *     visitorName: string
       *     // 访客类型（1 Contractor 2 Visitor）
       *     // [required]
       *     visitorType: string
       *   }
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      detailUsingGET<
        Config extends Alova2MethodConfig<R_Visitor_> & {
          params: {
            /**
             * id
             */
            id?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<R_Visitor_, 'general.detailUsingGET', Config>;
      /**
       * ---
       *
       * [GET] 根据企业微信code查询手机号
       *
       * **path:** /visitor/getUserIdByCode
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // code
       *   code?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   data?: object
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      getMobileByCodeUsingGET<
        Config extends Alova2MethodConfig<R> & {
          params: {
            /**
             * code
             */
            code?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<R, 'general.getMobileByCodeUsingGET', Config>;
      /**
       * ---
       *
       * [GET] 取消访问申请
       *
       * **path:** /visitor/mobile/cancel
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // id
       *   id?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   data?: object
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      cancelUsingGET<
        Config extends Alova2MethodConfig<R> & {
          params: {
            /**
             * id
             */
            id?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<R, 'general.cancelUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 被访人审批
       *
       * **path:** /visitor/mobile/examine
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 审批意见
       *   approvalOpinions?: string
       *   // 审批时间
       *   // [required]
       *   approvalTime: string
       *   // 创建时间
       *   // [required]
       *   createTime: string
       *   // 删除标识
       *   deleted?: number
       *   // 邮箱
       *   email?: string
       *   // 性别 unknown-未知,male-男性,female-女性）
       *   gender?: string
       *   // 主键
       *   id?: number
       *   // 证件号码
       *   identityNo?: string
       *   // 证件类型（1-身份证,99-其他）
       *   identityType?: string
       *   // 是否同意
       *   isAgree?: string
       *   // 是否审批
       *   isApproval?: string
       *   // 是否取消
       *   isCancel?: string
       *   // 手机号
       *   // [required]
       *   phone: string
       *   // 车牌号码
       *   // [required]
       *   plateNo: string
       *   // 原因
       *   reason?: string
       *   // 受访者姓名
       *   // [required]
       *   receptionistName: string
       *   // 受访者手机号
       *   // [required]
       *   receptionistPhone: string
       *   // 受访者企业微信userId
       *   // [required]
       *   receptionistUserId: string
       *   // 访问开始时间
       *   // [required]
       *   validBeginTime: string
       *   // 访问结束时间
       *   // [required]
       *   validEndTime: string
       *   // 访客人数
       *   // [required]
       *   visitorCount: number
       *   // 访客单位
       *   // [required]
       *   visitorDepartment: string
       *   // 访客姓名
       *   // [required]
       *   visitorName: string
       *   // 访客类型（1 Contractor 2 Visitor）
       *   // [required]
       *   visitorType: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   data?: object
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      examineUsingPOST<
        Config extends Alova2MethodConfig<R> & {
          data: Visitor;
        }
      >(
        config: Config
      ): Alova2Method<R, 'general.examineUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 根据手机号企业微信用户信息
       *
       * **path:** /visitor/mobile/getUserByPhone
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // phone
       *   phone?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   data?: object
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      getUserByPhoneUsingGET<
        Config extends Alova2MethodConfig<R> & {
          params: {
            /**
             * phone
             */
            phone?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<R, 'general.getUserByPhoneUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 小程序登录
       *
       * **path:** /visitor/mobile/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   code?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   data?: object
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      mobileLoginUsingPOST<
        Config extends Alova2MethodConfig<R> & {
          data: Phone;
        }
      >(
        config: Config
      ): Alova2Method<R, 'general.mobileLoginUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 小程序查询列表
       *
       * **path:** /visitor/mobile/queryPage
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 审批意见
       *   approvalOpinions?: string
       *   // 审批时间
       *   // [required]
       *   approvalTime: string
       *   // 创建时间
       *   // [required]
       *   createTime: string
       *   // 删除标识
       *   deleted?: number
       *   // 邮箱
       *   email?: string
       *   // 性别 unknown-未知,male-男性,female-女性）
       *   gender?: string
       *   // 主键
       *   id?: number
       *   // 证件号码
       *   identityNo?: string
       *   // 证件类型（1-身份证,99-其他）
       *   identityType?: string
       *   // 是否同意
       *   isAgree?: string
       *   // 是否审批
       *   isApproval?: string
       *   // 是否取消
       *   isCancel?: string
       *   pageNum?: number
       *   pageSize?: number
       *   // 手机号
       *   // [required]
       *   phone: string
       *   // 车牌号码
       *   // [required]
       *   plateNo: string
       *   // 原因
       *   reason?: string
       *   // 受访者姓名
       *   // [required]
       *   receptionistName: string
       *   // 受访者手机号
       *   // [required]
       *   receptionistPhone: string
       *   // 受访者企业微信userId
       *   // [required]
       *   receptionistUserId: string
       *   // 访问开始时间
       *   // [required]
       *   validBeginTime: string
       *   // 访问结束时间
       *   // [required]
       *   validEndTime: string
       *   // 访客人数
       *   // [required]
       *   visitorCount: number
       *   // 访客单位
       *   // [required]
       *   visitorDepartment: string
       *   // 访客姓名
       *   // [required]
       *   visitorName: string
       *   // 访客类型（1 Contractor 2 Visitor）
       *   // [required]
       *   visitorType: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   // [title] Page«Visitor»
       *   data?: {
       *     countId?: string
       *     current?: number
       *     maxLimit?: number
       *     optimizeCountSql?: boolean
       *     orders?: Array<{
       *       asc?: boolean
       *       column?: string
       *     }>
       *     pages?: number
       *     records?: Array<{
       *       // 审批意见
       *       approvalOpinions?: string
       *       // 审批时间
       *       // [required]
       *       approvalTime: string
       *       // 创建时间
       *       // [required]
       *       createTime: string
       *       // 删除标识
       *       deleted?: number
       *       // 邮箱
       *       email?: string
       *       // 性别 unknown-未知,male-男性,female-女性）
       *       gender?: string
       *       // 主键
       *       id?: number
       *       // 证件号码
       *       identityNo?: string
       *       // 证件类型（1-身份证,99-其他）
       *       identityType?: string
       *       // 是否同意
       *       isAgree?: string
       *       // 是否审批
       *       isApproval?: string
       *       // 是否取消
       *       isCancel?: string
       *       // 手机号
       *       // [required]
       *       phone: string
       *       // 车牌号码
       *       // [required]
       *       plateNo: string
       *       // 原因
       *       reason?: string
       *       // 受访者姓名
       *       // [required]
       *       receptionistName: string
       *       // 受访者手机号
       *       // [required]
       *       receptionistPhone: string
       *       // 受访者企业微信userId
       *       // [required]
       *       receptionistUserId: string
       *       // 访问开始时间
       *       // [required]
       *       validBeginTime: string
       *       // 访问结束时间
       *       // [required]
       *       validEndTime: string
       *       // 访客人数
       *       // [required]
       *       visitorCount: number
       *       // 访客单位
       *       // [required]
       *       visitorDepartment: string
       *       // 访客姓名
       *       // [required]
       *       visitorName: string
       *       // 访客类型（1 Contractor 2 Visitor）
       *       // [required]
       *       visitorType: string
       *     }>
       *     searchCount?: boolean
       *     size?: number
       *     total?: number
       *   }
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      mobileQueryPageUsingGET<
        Config extends Alova2MethodConfig<R_Page_Visitor_> & {
          params: {
            /**
             * 审批意见
             */
            approvalOpinions?: string;
            /**
             * 审批时间
             * [required]
             */
            approvalTime: string;
            /**
             * 创建时间
             * [required]
             */
            createTime: string;
            /**
             * 删除标识
             */
            deleted?: number;
            /**
             * 邮箱
             */
            email?: string;
            /**
             * 性别 unknown-未知,male-男性,female-女性）
             */
            gender?: string;
            /**
             * 主键
             */
            id?: number;
            /**
             * 证件号码
             */
            identityNo?: string;
            /**
             * 证件类型（1-身份证,99-其他）
             */
            identityType?: string;
            /**
             * 是否同意
             */
            isAgree?: string;
            /**
             * 是否审批
             */
            isApproval?: string;
            /**
             * 是否取消
             */
            isCancel?: string;
            pageNum?: number;
            pageSize?: number;
            /**
             * 手机号
             * [required]
             */
            phone: string;
            /**
             * 车牌号码
             * [required]
             */
            plateNo: string;
            /**
             * 原因
             */
            reason?: string;
            /**
             * 受访者姓名
             * [required]
             */
            receptionistName: string;
            /**
             * 受访者手机号
             * [required]
             */
            receptionistPhone: string;
            /**
             * 受访者企业微信userId
             * [required]
             */
            receptionistUserId: string;
            /**
             * 访问开始时间
             * [required]
             */
            validBeginTime: string;
            /**
             * 访问结束时间
             * [required]
             */
            validEndTime: string;
            /**
             * 访客人数
             * [required]
             */
            visitorCount: number;
            /**
             * 访客单位
             * [required]
             */
            visitorDepartment: string;
            /**
             * 访客姓名
             * [required]
             */
            visitorName: string;
            /**
             * 访客类型（1 Contractor 2 Visitor）
             * [required]
             */
            visitorType: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<R_Page_Visitor_, 'general.mobileQueryPageUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 发起访客申请
       *
       * **path:** /visitor/mobile/visitRequest
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 审批意见
       *   approvalOpinions?: string
       *   // 审批时间
       *   // [required]
       *   approvalTime: string
       *   // 创建时间
       *   // [required]
       *   createTime: string
       *   // 删除标识
       *   deleted?: number
       *   // 邮箱
       *   email?: string
       *   // 性别 unknown-未知,male-男性,female-女性）
       *   gender?: string
       *   // 主键
       *   id?: number
       *   // 证件号码
       *   identityNo?: string
       *   // 证件类型（1-身份证,99-其他）
       *   identityType?: string
       *   // 是否同意
       *   isAgree?: string
       *   // 是否审批
       *   isApproval?: string
       *   // 是否取消
       *   isCancel?: string
       *   // 手机号
       *   // [required]
       *   phone: string
       *   // 车牌号码
       *   // [required]
       *   plateNo: string
       *   // 原因
       *   reason?: string
       *   // 受访者姓名
       *   // [required]
       *   receptionistName: string
       *   // 受访者手机号
       *   // [required]
       *   receptionistPhone: string
       *   // 受访者企业微信userId
       *   // [required]
       *   receptionistUserId: string
       *   // 访问开始时间
       *   // [required]
       *   validBeginTime: string
       *   // 访问结束时间
       *   // [required]
       *   validEndTime: string
       *   // 访客人数
       *   // [required]
       *   visitorCount: number
       *   // 访客单位
       *   // [required]
       *   visitorDepartment: string
       *   // 访客姓名
       *   // [required]
       *   visitorName: string
       *   // 访客类型（1 Contractor 2 Visitor）
       *   // [required]
       *   visitorType: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   // [title] Visitor
       *   // 访客信息实体类
       *   data?: {
       *     // 审批意见
       *     approvalOpinions?: string
       *     // 审批时间
       *     // [required]
       *     approvalTime: string
       *     // 创建时间
       *     // [required]
       *     createTime: string
       *     // 删除标识
       *     deleted?: number
       *     // 邮箱
       *     email?: string
       *     // 性别 unknown-未知,male-男性,female-女性）
       *     gender?: string
       *     // 主键
       *     id?: number
       *     // 证件号码
       *     identityNo?: string
       *     // 证件类型（1-身份证,99-其他）
       *     identityType?: string
       *     // 是否同意
       *     isAgree?: string
       *     // 是否审批
       *     isApproval?: string
       *     // 是否取消
       *     isCancel?: string
       *     // 手机号
       *     // [required]
       *     phone: string
       *     // 车牌号码
       *     // [required]
       *     plateNo: string
       *     // 原因
       *     reason?: string
       *     // 受访者姓名
       *     // [required]
       *     receptionistName: string
       *     // 受访者手机号
       *     // [required]
       *     receptionistPhone: string
       *     // 受访者企业微信userId
       *     // [required]
       *     receptionistUserId: string
       *     // 访问开始时间
       *     // [required]
       *     validBeginTime: string
       *     // 访问结束时间
       *     // [required]
       *     validEndTime: string
       *     // 访客人数
       *     // [required]
       *     visitorCount: number
       *     // 访客单位
       *     // [required]
       *     visitorDepartment: string
       *     // 访客姓名
       *     // [required]
       *     visitorName: string
       *     // 访客类型（1 Contractor 2 Visitor）
       *     // [required]
       *     visitorType: string
       *   }
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      visitRequestUsingPOST<
        Config extends Alova2MethodConfig<R_Visitor_> & {
          data: Visitor;
        }
      >(
        config: Config
      ): Alova2Method<R_Visitor_, 'general.visitRequestUsingPOST', Config>;
      /**
       * ---
       *
       * [POST] pc登录
       *
       * **path:** /visitor/pc/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password?: string
       *   username?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   data?: object
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      pcLoginUsingPOST<
        Config extends Alova2MethodConfig<R> & {
          data: User;
        }
      >(
        config: Config
      ): Alova2Method<R, 'general.pcLoginUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 访客申请信息分页
       *
       * **path:** /visitor/queryPage
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 审批意见
       *   approvalOpinions?: string
       *   // 审批时间
       *   // [required]
       *   approvalTime: string
       *   // 创建时间
       *   // [required]
       *   createTime: string
       *   // 删除标识
       *   deleted?: number
       *   // 邮箱
       *   email?: string
       *   // 性别 unknown-未知,male-男性,female-女性）
       *   gender?: string
       *   // 主键
       *   id?: number
       *   // 证件号码
       *   identityNo?: string
       *   // 证件类型（1-身份证,99-其他）
       *   identityType?: string
       *   // 是否同意
       *   isAgree?: string
       *   // 是否审批
       *   isApproval?: string
       *   // 是否取消
       *   isCancel?: string
       *   pageNum?: number
       *   pageSize?: number
       *   // 手机号
       *   // [required]
       *   phone: string
       *   // 车牌号码
       *   // [required]
       *   plateNo: string
       *   // 原因
       *   reason?: string
       *   // 受访者姓名
       *   // [required]
       *   receptionistName: string
       *   // 受访者手机号
       *   // [required]
       *   receptionistPhone: string
       *   // 受访者企业微信userId
       *   // [required]
       *   receptionistUserId: string
       *   // 访问开始时间
       *   // [required]
       *   validBeginTime: string
       *   // 访问结束时间
       *   // [required]
       *   validEndTime: string
       *   // 访客人数
       *   // [required]
       *   visitorCount: number
       *   // 访客单位
       *   // [required]
       *   visitorDepartment: string
       *   // 访客姓名
       *   // [required]
       *   visitorName: string
       *   // 访客类型（1 Contractor 2 Visitor）
       *   // [required]
       *   visitorType: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   data?: object
       *   msg?: string
       *   status?: string
       * }
       * ```
       */
      queryPageUsingGET<
        Config extends Alova2MethodConfig<R> & {
          params: {
            /**
             * 审批意见
             */
            approvalOpinions?: string;
            /**
             * 审批时间
             * [required]
             */
            approvalTime: string;
            /**
             * 创建时间
             * [required]
             */
            createTime: string;
            /**
             * 删除标识
             */
            deleted?: number;
            /**
             * 邮箱
             */
            email?: string;
            /**
             * 性别 unknown-未知,male-男性,female-女性）
             */
            gender?: string;
            /**
             * 主键
             */
            id?: number;
            /**
             * 证件号码
             */
            identityNo?: string;
            /**
             * 证件类型（1-身份证,99-其他）
             */
            identityType?: string;
            /**
             * 是否同意
             */
            isAgree?: string;
            /**
             * 是否审批
             */
            isApproval?: string;
            /**
             * 是否取消
             */
            isCancel?: string;
            pageNum?: number;
            pageSize?: number;
            /**
             * 手机号
             * [required]
             */
            phone: string;
            /**
             * 车牌号码
             * [required]
             */
            plateNo: string;
            /**
             * 原因
             */
            reason?: string;
            /**
             * 受访者姓名
             * [required]
             */
            receptionistName: string;
            /**
             * 受访者手机号
             * [required]
             */
            receptionistPhone: string;
            /**
             * 受访者企业微信userId
             * [required]
             */
            receptionistUserId: string;
            /**
             * 访问开始时间
             * [required]
             */
            validBeginTime: string;
            /**
             * 访问结束时间
             * [required]
             */
            validEndTime: string;
            /**
             * 访客人数
             * [required]
             */
            visitorCount: number;
            /**
             * 访客单位
             * [required]
             */
            visitorDepartment: string;
            /**
             * 访客姓名
             * [required]
             */
            visitorName: string;
            /**
             * 访客类型（1 Contractor 2 Visitor）
             * [required]
             */
            visitorType: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<R, 'general.queryPageUsingGET', Config>;
    };
  }

  var Apis: Apis;
}
